# Generated by Django 5.2.7 on 2025-12-09 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_usermodesettings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="is_transformed_to_quest",
        ),
    ]
