# Generated by Django 5.2.7 on 2026-01-04 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_quests_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quests",
            name="match",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quests",
                to="users.match",
            ),
        ),
    ]
