# Generated by Django 5.2.7 on 2025-12-11 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_task_is_transformed_to_quest"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_free",
            field=models.BooleanField(default=False),
        ),
    ]
