# Generated by Django 5.2.7 on 2025-12-11 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_task_is_free"),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("successful", "successful"),
                            ("user1_missed", "user1_missed"),
                            ("user2_missed", "user2_missed"),
                            ("expired", "expired"),
                        ],
                        default="successful",
                        max_length=20,
                    ),
                ),
                ("matched_at", models.DateTimeField(blank=True, null=True)),
                ("user1_rating", models.IntegerField(blank=True, null=True)),
                ("user2_rating", models.IntegerField(blank=True, null=True)),
                (
                    "user1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_as_user1",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_as_user2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "match",
                "verbose_name_plural": "matches",
                "indexes": [
                    models.Index(
                        fields=["matched_at"], name="users_match_matched_747486_idx"
                    )
                ],
            },
        ),
    ]
