# Generated by Django 5.2.7 on 2025-12-11 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_match"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quests",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location_name", models.CharField(blank=True, max_length=255)),
                ("activity", models.CharField(max_length=255)),
                (
                    "location_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=10, null=True
                    ),
                ),
                (
                    "location_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=11, null=True
                    ),
                ),
                ("quest_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "pending"), ("completed", "completed")],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("xp_reward", models.IntegerField(blank=True, default=0, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "match",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quests",
                        to="users.match",
                    ),
                ),
            ],
            options={
                "verbose_name": "quest",
                "verbose_name_plural": "quests",
                "indexes": [
                    models.Index(
                        fields=["quest_date"], name="users_quest_quest_d_5b2036_idx"
                    )
                ],
            },
        ),
    ]
