# Generated by Django 5.2.7 on 2025-12-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_preference_userpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='quests',
            name='hint_user1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quests',
            name='hint_user2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_matched',
            field=models.BooleanField(default=False),
        ),
    ]
